[workspace]

members = [
    "decide-proto",
    "decide-core",
    "components/lights",
    "components/house_light",
    "components/stepper_motor",
    "components/peckboard",
    "components/sound",
]
