[package]
name = "decide-core"
version = "0.1.0"
authors = ["Jonah Weissman <jonahrweissman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decide-proto = { path = "../decide-proto" }
lights = { path = "../components/lights" }
tmq = "0.3.0"
zmq = "0.9.2"
log = "0.4.14"
tokio = { version = "1.13", features = ["full"] }
pretty_env_logger = "0.4.0"
prost = "0.9"
prost-types = "0.9"
anyhow = "1.0"
directories = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
futures = "0.3.17"
serde-value = "0.7.0"
sha3 = "0.9.1"
generic-array = "0.14.4"
num-traits = "0.2.14"
tokio-stream = "0.1.8"

[dev-dependencies]
console-subscriber = { git = "https://github.com/tokio-rs/console" }
rand = "0.7"
